syntax = "proto3";

package profile.v1;

option go_package = "guiforcores/proto/profile/v1";

import "profile/v1/profile.proto";

message ListProfilesRequest {}

message ListProfilesResponse {
  repeated Profile profiles = 1;
}

message GetProfileRequest {
  string id = 1;
}

message GetProfileResponse {
  Profile profile = 1;
}

message CreateProfileRequest {
  Profile profile = 1;
}

message CreateProfileResponse {
  Profile profile = 1;
}

message UpdateProfileRequest {
  Profile profile = 1;
}

message UpdateProfileResponse {
  Profile profile = 1;
}

message DeleteProfileRequest {
  string id = 1;
}

message DeleteProfileResponse {}

message SaveProfilesRequest {
  repeated Profile profiles = 1;
}

message SaveProfilesResponse {
  repeated Profile profiles = 1;
}

service ProfileService {
  rpc ListProfiles(ListProfilesRequest) returns (ListProfilesResponse);
  rpc GetProfile(GetProfileRequest) returns (GetProfileResponse);
  rpc CreateProfile(CreateProfileRequest) returns (CreateProfileResponse);
  rpc UpdateProfile(UpdateProfileRequest) returns (UpdateProfileResponse);
  rpc DeleteProfile(DeleteProfileRequest) returns (DeleteProfileResponse);
  rpc SaveProfiles(SaveProfilesRequest) returns (SaveProfilesResponse);
}
